version: 2.1

jobs:
  run-migrations:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run: yum install curl 
      - run: yum awscli
      - run:
          name: Run migrations
          command: |
            curl -H "token: 2e0e93c3-63c8-4a64-b59e-58672ea510d7" --request GET https://api.memstash.io/values/hello

workflows:
  my_workflow:
    jobs:
      - run-migrations