version: 2.1

jobs:
  run-migrations:
    docker:
      #- image: cimg/base:2021.07
    machine: true
    steps:
      - checkout 
      - run: sudo apt install curl gzip tar
      - run:
          name: Install dependencies
          command: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/0.20.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            


workflows:
  my_workflow:
    jobs:
      - run-migrations