version: 2.1

jobs:
  run-migrations:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            sudo yum update
            sudo yum upgrade
            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash - 
            yum install -y nodejs
            yum install npm

workflows:
  my_workflow:
    jobs:
      - run-migrations