version: 2.1

jobs:
  run-migrations:
    docker:
      - image: ubuntu-2004:202010-01
    steps:
      - checkout 
      - run: sudo apt install curl gzip tar
      - run:
          name: Install dependencies
          command: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            


workflows:
  my_workflow:
    jobs:
      - run-migrations