version: 2.1

jobs:
  run-migrations:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run : apk add --update nodejs npm
      - run:
          name: Run migrations
          command: |
            apk add --update ansible

workflows:
  my_workflow:
    jobs:
      - run-migrations