version: 2.1

jobs:
  run-migrations:
    docker:
      - image: amazon/aws-cli 
    steps:
      - checkout 
      - run: yum -y install tar gzip curl wget
      - run:
          name: Install dependencies
          command: |
            curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/latest_release/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            


workflows:
  my_workflow:
    jobs:
      - run-migrations