version: 2.1

jobs:
  run-migrations:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            npm migration > migration.txt
            cat migration.txt
workflows:
  my_workflow:
    jobs:
      - run-migrations