version: 2.1

jobs:
  run-migrations:
    docker:
      - image: amazon/aws-cli
    steps:
      - checkout 
      - run: yum -y install tar gzip curl wget sudo
      - run:
          name: Install dependencies
          command: |
            sudo curl --silent --location "https://github.com/weaveworks/eksctl/releases/download/0.63.0/eksctl_Linux_amd64.tar.gz" | tar xz -C /tmp
            


workflows:
  my_workflow:
    jobs:
      - run-migrations