version: 2.1

jobs:
  run-migrations:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - run:
          name: Run migrations
          command: |
            apk add --update ansible
            yum update
            yum upgrade
            yum install sudo -y
            curl -sL https://rpm.nodesource.com/setup_13.x | sudo bash - 
            yum install -y nodejs
            npm i

workflows:
  my_workflow:
    jobs:
      - run-migrations